#!/usr/bin/env python
from torutils import controller
from sys import argv

if len(argv) == 1:
	print 'Usage: %s name [name2] ...\n' % argv[0]
	print controller.get_info('info/names')
elif len(argv) == 2:
	print controller.get_info(argv[1])
else:
	infos = controller.get_info(argv[1:])
	for info in argv[1:]:
		print "%s %s" % (info, infos[info])


